/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flashablezipcreator.UserInterface;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;

/**
 *
 * @author Nikhil
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public JDialog dialog;

    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        dialog = new JDialog(this, "About Us", true);
        dialog.setResizable(false);
        mainPanel = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblRajatImage = new javax.swing.JLabel();
        lblAboutRajat = new javax.swing.JLabel();
        lblAboutNikhil = new javax.swing.JLabel();
        lblAboutUs = new javax.swing.JLabel();
        lblNikhilImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblRajatImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flashablezipcreator/2359723.jpg"))); // NOI18N

        lblAboutRajat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblAboutRajat.setText("<HTML> <RIGHT><B>Rajat Patel</B></RIGHT>  <br> I am <a href=\\\"https://forum.xda-developers.com/member.php?u=1852653\\\">Rajat Patel</a>, contributor to the development of this tool, xda senior member, geek by heart, Business Analyst by Profession, football lover & Chelsea fan.<br>  Foreseen by Nikhil and coded by me and him together is this tool, saving your time in creating flashable zips for Android Recovery and lets you concentrate more on the actual work than creating a flashable!<br>  Happy flashing! </HTML>");

        lblAboutNikhil.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblAboutNikhil.setText("<HTML> <B>Nikhil Menghani</B>  <br> I am <a href=\"https://forum.xda-developers.com/member.php?u=4867515\">Nikhil Menghani</a>, creator of this tool, xda senior member, programming enthusiast, a software developer, chess player, cricket lover. I try to ease my life by creating utilities.<br>  What you are using is one of my utilities, it will get you a flashable zip which you can directly flash in your phone, saving your time in writing flawless aroma script, updater script and of course putting all the files at right place.<br>  Happy flashing! </HTML>");

        lblAboutUs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAboutUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAboutUs.setText("About Us");

        lblNikhilImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flashablezipcreator/1549450_687091887991785_1258867375_n.jpg"))); // NOI18N

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
                panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelHeaderLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lblAboutRajat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblRajatImage))
                                        .addGroup(panelHeaderLayout.createSequentialGroup()
                                                .addGap(246, 246, 246)
                                                .addComponent(lblAboutUs)
                                                .addGap(0, 264, Short.MAX_VALUE))
                                        .addGroup(panelHeaderLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lblNikhilImage)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblAboutNikhil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
                panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                                .addComponent(lblAboutUs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNikhilImage, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAboutNikhil, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblRajatImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(lblAboutRajat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialog.getContentPane().add(mainPanel);
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                dialog.dispose();
            }
        });
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel lblAboutNikhil;
    private javax.swing.JLabel lblAboutRajat;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblNikhilImage;
    private javax.swing.JLabel lblRajatImage;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration                   
}
