/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flashablezipcreator.UserInterface;

/**
 *
 * @author Nikhil
 */
public class CustomGroupUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomGroupUI
     */
    public CustomGroupUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        panelPermissions = new javax.swing.JPanel();
        cbOthersX = new javax.swing.JCheckBox();
        cbOwnerW = new javax.swing.JCheckBox();
        lblPermInDigit = new javax.swing.JLabel();
        cbGroupW = new javax.swing.JCheckBox();
        cbSticky = new javax.swing.JCheckBox();
        lblR = new javax.swing.JLabel();
        lblOwner = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        cbOwnerR = new javax.swing.JCheckBox();
        lblPermissions = new javax.swing.JLabel();
        llblW = new javax.swing.JLabel();
        lblGroup = new javax.swing.JLabel();
        cbGroupX = new javax.swing.JCheckBox();
        cbSetuid = new javax.swing.JCheckBox();
        cbGroupR = new javax.swing.JCheckBox();
        cbSetgid = new javax.swing.JCheckBox();
        lblPermInString = new javax.swing.JLabel();
        cbOthersW = new javax.swing.JCheckBox();
        cbOthersR = new javax.swing.JCheckBox();
        lblOthers = new javax.swing.JLabel();
        cbX = new javax.swing.JCheckBox();
        panelGroupDetails = new javax.swing.JPanel();
        lblGroupName = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();
        lblInstallLocation = new javax.swing.JLabel();
        txtInstallLocation = new javax.swing.JTextField();
        lblFileInstructions = new javax.swing.JLabel();
        cbFileInstructions = new javax.swing.JComboBox<>();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        cbRecursive = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelMain.setBackground(new java.awt.Color(255, 255, 255));

        panelHeader.setBackground(new java.awt.Color(153, 153, 0));

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("   Add Group");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdd.setContentAreaFilled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        panelPermissions.setBackground(new java.awt.Color(255, 255, 255));

        cbOthersX.setBackground(new java.awt.Color(255, 255, 255));

        cbOwnerW.setBackground(new java.awt.Color(255, 255, 255));

        lblPermInDigit.setBackground(new java.awt.Color(255, 255, 255));
        lblPermInDigit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPermInDigit.setText("666");
        lblPermInDigit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cbGroupW.setBackground(new java.awt.Color(255, 255, 255));

        cbSticky.setBackground(new java.awt.Color(255, 255, 255));
        cbSticky.setText("sticky");

        lblR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblR.setText(" R");
        lblR.setPreferredSize(new java.awt.Dimension(21, 21));

        lblOwner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOwner.setText("Owner");

        lblX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblX.setText("  X");
        lblX.setPreferredSize(new java.awt.Dimension(21, 21));

        cbOwnerR.setBackground(new java.awt.Color(255, 255, 255));

        lblPermissions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPermissions.setText("Permissions");

        llblW.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        llblW.setText(" W");
        llblW.setPreferredSize(new java.awt.Dimension(21, 21));

        lblGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGroup.setText("Group");

        cbGroupX.setBackground(new java.awt.Color(255, 255, 255));

        cbSetuid.setBackground(new java.awt.Color(255, 255, 255));
        cbSetuid.setText("setuid");

        cbGroupR.setBackground(new java.awt.Color(255, 255, 255));

        cbSetgid.setBackground(new java.awt.Color(255, 255, 255));
        cbSetgid.setText("setgid");

        lblPermInString.setBackground(new java.awt.Color(255, 255, 255));
        lblPermInString.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPermInString.setText("-rw-rw-rw-");
        lblPermInString.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cbOthersW.setBackground(new java.awt.Color(255, 255, 255));

        cbOthersR.setBackground(new java.awt.Color(255, 255, 255));

        lblOthers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOthers.setText("Others");

        cbX.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelPermissionsLayout = new javax.swing.GroupLayout(panelPermissions);
        panelPermissions.setLayout(panelPermissionsLayout);
        panelPermissionsLayout.setHorizontalGroup(
            panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPermissionsLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPermissionsLayout.createSequentialGroup()
                        .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGroup)
                            .addComponent(lblOthers)
                            .addComponent(lblOwner))
                        .addGap(18, 18, 18)
                        .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPermissionsLayout.createSequentialGroup()
                                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPermissionsLayout.createSequentialGroup()
                                        .addComponent(cbGroupR)
                                        .addGap(40, 40, 40)
                                        .addComponent(cbGroupW))
                                    .addGroup(panelPermissionsLayout.createSequentialGroup()
                                        .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbOwnerR))
                                        .addGap(40, 40, 40)
                                        .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbOwnerW)
                                            .addComponent(llblW, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40)
                                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbX)
                                    .addComponent(cbGroupX)
                                    .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelPermissionsLayout.createSequentialGroup()
                                .addComponent(cbOthersR)
                                .addGap(40, 40, 40)
                                .addComponent(cbOthersW)
                                .addGap(40, 40, 40)
                                .addComponent(cbOthersX))
                            .addGroup(panelPermissionsLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPermissionsLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(lblPermInDigit))
                                    .addGroup(panelPermissionsLayout.createSequentialGroup()
                                        .addComponent(cbSetgid)
                                        .addGap(38, 38, 38)
                                        .addComponent(cbSticky))
                                    .addComponent(lblPermInString))))
                        .addGap(20, 20, 20))
                    .addComponent(cbSetuid)
                    .addGroup(panelPermissionsLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblPermissions)))
                .addGap(33, 33, 33))
        );
        panelPermissionsLayout.setVerticalGroup(
            panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPermissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPermissions)
                .addGap(18, 18, 18)
                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llblW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbOwnerR)
                    .addComponent(cbOwnerW)
                    .addComponent(cbX)
                    .addComponent(lblOwner, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGroup)
                    .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbGroupR)
                        .addComponent(cbGroupW)
                        .addComponent(cbGroupX)))
                .addGap(18, 18, 18)
                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOthers)
                    .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbOthersR)
                        .addComponent(cbOthersW)
                        .addComponent(cbOthersX)))
                .addGap(18, 18, 18)
                .addGroup(panelPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSetuid)
                    .addComponent(cbSticky)
                    .addComponent(cbSetgid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPermInDigit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPermInString)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelGroupDetails.setBackground(new java.awt.Color(255, 255, 255));

        lblGroupName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGroupName.setText("Group Name ");

        txtGroupName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblInstallLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInstallLocation.setText("Install Location");

        txtInstallLocation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblFileInstructions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFileInstructions.setText("File Install Instructions");

        cbFileInstructions.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbFileInstructions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any One FIle Per Group", "Multiple Files Per Group" }));
        cbFileInstructions.setOpaque(false);

        lblDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescription.setText("Description");

        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelGroupDetailsLayout = new javax.swing.GroupLayout(panelGroupDetails);
        panelGroupDetails.setLayout(panelGroupDetailsLayout);
        panelGroupDetailsLayout.setHorizontalGroup(
            panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroupDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGroupName)
                    .addComponent(lblInstallLocation)
                    .addComponent(txtInstallLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtGroupName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbFileInstructions, javax.swing.GroupLayout.Alignment.TRAILING, 0, 198, Short.MAX_VALUE))
                    .addComponent(lblDescription)
                    .addComponent(lblFileInstructions))
                .addContainerGap())
        );
        panelGroupDetailsLayout.setVerticalGroup(
            panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroupDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGroupName)
                    .addComponent(lblFileInstructions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFileInstructions)
                    .addGroup(panelGroupDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGroupDetailsLayout.createSequentialGroup()
                        .addGroup(panelGroupDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInstallLocation)
                            .addComponent(lblDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInstallLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cbRecursive.setBackground(new java.awt.Color(255, 255, 255));
        cbRecursive.setText("Recursive");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cbRecursive)
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelGroupDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelPermissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelGroupDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelPermissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRecursive, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomGroupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomGroupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomGroupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomGroupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomGroupUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cbFileInstructions;
    private javax.swing.JCheckBox cbGroupR;
    private javax.swing.JCheckBox cbGroupW;
    private javax.swing.JCheckBox cbGroupX;
    private javax.swing.JCheckBox cbOthersR;
    private javax.swing.JCheckBox cbOthersW;
    private javax.swing.JCheckBox cbOthersX;
    private javax.swing.JCheckBox cbOwnerR;
    private javax.swing.JCheckBox cbOwnerW;
    private javax.swing.JCheckBox cbRecursive;
    private javax.swing.JCheckBox cbSetgid;
    private javax.swing.JCheckBox cbSetuid;
    private javax.swing.JCheckBox cbSticky;
    private javax.swing.JCheckBox cbX;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFileInstructions;
    private javax.swing.JLabel lblGroup;
    private javax.swing.JLabel lblGroupName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInstallLocation;
    private javax.swing.JLabel lblOthers;
    private javax.swing.JLabel lblOwner;
    private javax.swing.JLabel lblPermInDigit;
    private javax.swing.JLabel lblPermInString;
    private javax.swing.JLabel lblPermissions;
    private javax.swing.JLabel lblR;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel llblW;
    private javax.swing.JPanel panelGroupDetails;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPermissions;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtGroupName;
    private javax.swing.JTextField txtInstallLocation;
    // End of variables declaration//GEN-END:variables
}
